#!/usr/bin/env python3
# lib/debug.py

from models.character import Character
from models.battle import Battle

def seed_database():
    Character.drop_table()
    Character.create_table()
    Battle.drop_table()
    Battle.create_table()

    Character.create("Deadpool", "Earth", "Healing Factor, Ninja Skills")
    Character.create("Spider-Man", "Manhattan", "Strength, Webbing, Agility")
    Character.create("Daredevil", "Manhattan", "Senses")
    Battle.create(1, 2, "Manhattan")
    Battle.create(1, 3, "Manhattan")

print("Database seeded!")
seed_database()
